services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: store_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - db
      - node

  db:
    image: mysql:8.0
    container_name: store_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_USER: store_user
      MYSQL_PASSWORD: store_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node:
    image: node:20
    container_name: store_node
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: sh -c "npm install && npm run build"


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: store_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    depends_on:
      - db
      
volumes:
  db_data:
